language: perl
perl:
  - 5.22
  - '5.20'
  - 5.18
  - 5.16
  - 5.14
  - 5.12
before_install:
  - perlbrew install-cpanm -f
install:
  - (cpanm -nq --dev Menlo) || cat ~/.cpanm/build.log
  - (cpanm --installdeps --with-develop -nq .) || cat ~/.cpanm/build.log
script:
  - prove -lr xt
cache:
  directories:
    - $HOME/.carmel
env:
  - TEST_CLEAN=
  - TEST_CLEAN=1
sudo: false
